name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.cicd_pipeline_aws_access_key_id }} # Change according to your region key name
          aws-secret-access-key: ${{ secrets.cicd_pipeline_aws_secret_access_key }} # Change according to your key name
          aws-region: us-east-1  # Change according to your region

      - name: Sync files to S3
        uses: aws-actions/s3-sync@v0.1.0
        with:
          args: --acl public-read --follow-symlinks
          bucket: synapselabs-s3bucket-gp # Replace with your S3 bucket name
          source-dir: './my_app'  # Adjust if your files are in a subdirectory

     
